
defmodule NimlerWrapper do
    def load_nif, do: :erlang.load_nif(to_charlist(Path.join(Path.dirname(__ENV__.file), "nif")), 0)

    def enif_is_atom(_a), do: raise "not implemented"
    def enif_is_binary(_a), do: raise "not implemented"
    def enif_is_current_process_alive(), do: raise "not implemented"
    def enif_is_empty_list(_a), do: raise "not implemented"
    def enif_is_exception(_a), do: raise "not implemented"
    def enif_is_fun(_a), do: raise "not implemented"
    def enif_is_identical(_a, _b), do: raise "not implemented"
    def enif_is_list(_a), do: raise "not implemented"
    def enif_is_map(_a), do: raise "not implemented"
    def enif_is_number(_a), do: raise "not implemented"
    def enif_is_pid(_a), do: raise "not implemented"
    def enif_is_pid_undefined(_a), do: raise "not implemented"
    def enif_is_port(_a), do: raise "not implemented"
    def enif_is_port_alive(_a), do: raise "not implemented"
    def enif_is_process_alive(_a), do: raise "not implemented"
    def enif_is_ref(_a), do: raise "not implemented"
    def enif_is_tuple(_a), do: raise "not implemented"
    def enif_make_atom(), do: "raise not implemented"
    def enif_make_existing_atom(), do: "raise not implemented"
    def enif_make_existing_atom_len(), do: "raise not implemented"
    def enif_make_int(), do: raise "not implemented"
    def enif_make_long(), do: raise "not implemented"
    def enif_make_int64(), do: raise "not implemented"
    def enif_make_uint(), do: raise "not implemented"
    def enif_make_ulong(), do: raise "not implemented"
    def enif_make_uint64(), do: raise "not implemented"
    def enif_make_double(), do: raise "not implemented"
    def enif_make_string(), do: raise "not implemented"
    def enif_make_string_len(), do: raise "not implemented"
    def enif_make_list(), do: raise "not implemented"
    def enif_make_list_cell(), do: raise "not implemented"
    def enif_make_list_from_array(), do: raise "not implemented"
    def enif_make_tuple(), do: raise "not implemented"
    def enif_make_tuple_from_array(), do: raise "not implemented"
    def enif_make_new_binary(), do: raise "not implemented"
    def enif_make_new_map(), do: raise "not implemented"
    def enif_make_map_from_arrays(), do: raise "not implemented"
    def enif_make_map_put(_a, _b, _c), do: raise "not implemented"
    def enif_make_map_remove(_a, _b), do: raise "not implemented"
    def enif_make_map_update(_a, _b, _c), do: raise "not implemented"
    def enif_make_copy(), do: raise "not implemented"
    def enif_make_pid(), do: raise "not implemented"
    def enif_make_ref(), do: raise "not implemented"
    def enif_make_reverse_list(), do: raise "not implemented"
    def enif_make_unique_integer(), do: raise "not implemented"
    def enif_get_map_value(_a, _b), do: raise "not implemented"
    def enif_get_map_size(_a), do: raise "not implemented"
    def enif_get_tuple(_a), do: raise "not implemented"
    def enif_get_list_length(_a), do: raise "not implemented"
    def enif_get_list_cell(_a), do: raise "not implemented"
    def enif_get_string(_a), do: raise "not implemented"
    def enif_get_int(_a), do: raise "not implemented"
    def enif_get_long(_a), do: raise "not implemented"
    def enif_get_int64(_a), do: raise "not implemented"
    def enif_get_uint(_a), do: raise "not implemented"
    def enif_get_ulong(_a), do: raise "not implemented"
    def enif_get_uint64(_a), do: raise "not implemented"
    def enif_get_double(_a), do: raise "not implemented"
    def enif_get_atom(_a), do: raise "not implemented"
    def enif_get_atom_length(_a), do: raise "not implemented"
    def enif_get_local_pid(_a), do: raise "not implemented"
    def enif_raise_exception(_a), do: raise "not implemented"
    def enif_fprintf(_a), do: raise "not implemented"
    def enif_snprintf(_a), do: raise "not implemented"
    def enif_system_info(), do: raise "not implemented"
    def enif_term_type(_a, _b, _c, _d, _e, _f), do: raise "not implemented"
    def enif_compare(_a, _b), do: raise "not implemented"
end
